# Generated by Django 4.2.7 on 2023-11-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(default='photos/Grande_punto_5tuerer.jpeg', null=True, upload_to='photos/'),
        ),
    ]
