# Generated by Django 4.2.7 on 2023-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo_url',
            field=models.CharField(default='photos/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(default='photos/default.png', null=True, upload_to='static/photos'),
        ),
    ]
